server:
  port: 5000
  servlet:
    encoding:
      charset: utf-8
      force: true
spring:
  datasource:
    url: jdbc:mariadb://mubwara.cx7tqebskxnq.ap-northeast-2.rds.amazonaws.com:3306/finaldb
    driver-class-name: org.mariadb.jdbc.Driver
    username: admin
    password: 12345678!
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none

logging:
  level:
    '[com.mtcoding.demo]': Info 



fileDir: "./image"